name: skeleton_text
description: A package that provides an easy way to add skeleton text loading animation in Flutter project.
version: 0.0.2
author: Mahen Gandhi<mahengandhi19@gmail.com>
homepage: https://github.com/imlegend19/Skeleton-Text

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
