name: skeleton_text
description: A package that provides an easy way to add skeleton text loading animation in Flutter project. This project is a part of 101Loop community.
version: 2.0.2
homepage: https://github.com/101Loop/Skeleton-Text

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
